config/routes.rb
SimpleWebiste::Application.routes.draw do

  resources :documents
  resources :notices
  resources :categories

  devise_for :users,  :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  root :to => 'home#index'
  
  match "/admin", to: "admin#index" 

end

app/models/notice.rb
class Notice < ActiveRecord::Base
	belongs_to :category

	has_attached_file :image, :styles => {:medium => "400x400>", :tumb => "200x200#"}

	validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_filter :authenticate_user!
  
  layout "admin_application"

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render json: @notice, status: :created, location: @notice }
      else
        format.html { render action: "new" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.haml
= form_for @notice, :html => {:multipart => true} do |f|
  -if @notice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@notice.errors.count, "error")} prohibited this notice from being saved:"
      %ul
        - @notice.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :category_id
    = f.collection_select :category_id, Category.all, :id, :name
  .field
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/notices/edit.html.haml
%h1 Editing notice

= render 'form'

= link_to 'Show', @notice
\|
= link_to 'Back', notices_path

app/views/notices/index.html.haml
%h1 Listing notices

%table
  %tr
    %th Title
    %th Content
    %th Category
    %th
    %th
    %th

  - @notices.each do |notice|
    %tr
      %td= notice.title
      %td= notice.content
      %td= notice.category.name
      %td= link_to 'Show', notice
      %td= link_to 'Edit', edit_notice_path(notice)
      %td= link_to 'Destroy', notice, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Notice', new_notice_path

app/views/notices/new.html.haml
%h1 New notice

= render 'form'

= link_to 'Back', notices_path

app/views/notices/show.html.haml
%p#notice= notice

%p
	%b= @notice.title
%p
	%b Content:
	= @notice.content
%p
	%b Category:
	= @notice.category.name
%p
	= image_tag @notice.image.url(:tumb)

= link_to 'Edit', edit_notice_path(@notice)
\|
= link_to 'Back', notices_path