config/routes.rb
SimpleWebiste::Application.routes.draw do

  resources :documents
  resources :notices
  resources :categories

  devise_for :users,  :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  root :to => 'home#index'
  
  match "/admin", to: "admin#index" 

end

app/models/document.rb
class Document < ActiveRecord::Base
	has_attached_file :file_doc

	validates_attachment_presence :file_doc
	validates_attachment_size :file_doc, :less_than => 10.megabytes
	validates_format_of :file_doc_file_name, :with => %r{\.(docx|doc|pdf)$}i
	#validates_attachment_content_type :file_doc, :content_type => 'text/plain'
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= form_for @document, :html => {:multipart => true} do |f|
  -if @document.errors.any?
    #error_explanation
      %h2= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.file_field :file_doc
  .actions
    = f.submit 'Save'

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%h1 Listing documents

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @documents.each do |document|
    %tr
      %td= document.name
      %td= document.description
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Document', new_document_path

app/views/documents/new.html.haml
%h1 New document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @document.name
%p
  %b Description:
  = @document.description
%p
  %b Document File:
  = link_to @document.file_doc.name , @document.file_doc.url

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path